CREATE TABLE TOPICS(ID INT PRIMARY KEY, NAME VARCHAR(255));
ALTER TABLE TOPICS ALTER COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE QUESTIONS(
	ID INT PRIMARY KEY,
	DIFFICULTY INT,
	TOPIC_ID INT,
	QUESTION VARCHAR(255),
	FOREIGN KEY(TOPIC_ID) REFERENCES TOPICS(ID)
);
ALTER TABLE QUESTIONS ALTER COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE QUIZZES(ID INT PRIMARY KEY, TITLE VARCHAR(255), QUESTIONS VARCHAR(255));
ALTER TABLE QUIZZES ALTER COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE STUDENTS(ID INT PRIMARY KEY, NAME VARCHAR(255));
ALTER TABLE STUDENTS ALTER COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE EXAMS(
	ID INT PRIMARY KEY,
	STUDENT_ID INT,
	QUIZ_ID INT,
	GRADE DECIMAL(18,2),
	FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(ID),
	FOREIGN KEY(QUIZ_ID) REFERENCES QUIZZES(ID)
);
ALTER TABLE EXAMS ALTER COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE ANSWERS(
	ID INT PRIMARY KEY,
	EXAM_ID INT,
	TEXT VARCHAR(255),
	QUESTION_ID INT,
	FOREIGN KEY(EXAM_ID) REFERENCES EXAMS(ID),
	FOREIGN KEY(QUESTION_ID) REFERENCES QUESTIONS(ID)
);
ALTER TABLE ANSWERS ALTER COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE MCQQUESTIONS(
	ID INT PRIMARY KEY,
	QUESTION_ID INT,
	FOREIGN KEY(QUESTION_ID) REFERENCES QUESTIONS(ID)
);
ALTER TABLE MCQQUESTIONS ALTER COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE MCQCHOICES(
	ID INT PRIMARY KEY,
	MCQQUESTION_ID INT,
	VALID BOOLEAN,
	CHOICE VARCHAR(255),
	FOREIGN KEY(MCQQUESTIONS_INT) REFERENCES MCQQUESTIONS(ID)
);
ALTER TABLE MCQCHOICES ALTER COLUMN ID INT AUTO_INCREMENT;

CREATE TABLE MCQANSWERS(
	ID INT PRIMARY KEY,
	EXAM_ID INT,
	MCQCHOICE_ID INT,
	FOREIGN KEY(EXAM_ID) REFERENCES EXAMS(ID),
	FOREIGN KEY(MCQCHOICE_ID) REFERENCES MCQCHOICES(ID),
);
ALTER TABLE MCQANSWERS ALTER COLUMN ID INT AUTO_INCREMENT;

